var worksorders = [
  {
    id: 1,
    client: "BIC",
    servicetype: "Repair",
    equipment: "Arburg",
    technician: "Victor",
    description: "This is the first work order",
    status: "Works Order",
    created: "2024-10-02",
    servicecall: { date: "2024-10-10", time: "10:00" },
    worksordernumber: "WO-001",
    worksorderdetails: [
      {
        Item: "Parts",
        Qoute: "QouteBarrel.pdf",
        price: "R6300",
        status: "Pending",
        date: "2024-10-11",
      },
      {
        Item: "Labour",
        technicians: "Victor",
        hours: "4",
        rate: "500",
        price: "R2000",
        status: "Accepted",
        date: "2024-10-12",
      },
      {
        Item: "Labour",
        technicians: "Lourens",
        hours: "6",
        rate: "500",
        price: "R3000",
        status: "Accepted",
        date: "2024-10-11",
      },
    ],
  },
  {
    id: 2,
    client: "Pharma-Pack",
    servicetype: "Repair",
    equipment: "Macquire",
    technician: "Gus",
    description: "Dryer not drying",
    status: "Service Call",
    created: "2024-10-03",
    servicecall: { date: "2024-10-15", time: "14:00" },
    worksordernumber: "WO-002",
    worksorderdetails: [],
  },
  {
    id: 3,
    client: "BIC",
    servicetype: "Repair",
    equipment: "Arburg",
    technician: "Lourens",
    description: "Straws paper like",
    status: "Please Approve",
    created: "2024-10-04",
    servicecall: { date: "2024-10-11", time: "09:00" },
    worksordernumber: "WO-003",
    worksorderdetails: [
      {
        Item: "Parts",
        Qoute: "parts.pdf",
        price: "R15000",
        status: "Accepted",
        date: "2024-10-11",
      },
      {
        Item: "Labour",
        technicians: "Gus",
        hours: "10",
        rate: "650",
        price: "R6500",
        status: "Accepted",
        date: "2024-10-12",
      },
    ],
  },
];
